/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

public class Prob2 {
	public static main(String args[]) {
		int sum = 0;
		num1 = 1;
		num2 = 2;
		
		while(fibo(num1, num2) < 40) {
			System.out.println(fibo(num1, num2);
		
	}
	
	public static int fibo(int prev1, int prev2) {
		return prev1 + prev2;
}